services:
  - type: web
    name: ai-hedge-fund-frontend
    runtime: static
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: REACT_APP_API_URL
        value: https://ai-hedge-fund-backend.onrender.com
      - key: REACT_APP_ENVIRONMENT
        value: production
      - key: GENERATE_SOURCEMAP
        value: "false"
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
